version: "3.9"
services:
  main:
    build: ./__external.siyuan
    command: ['--workspace=/siyuan/workspace/', '--accessAuthCode=${ZEUS_AUTH_CODE}']
    ports:
      - 6806:6806
    volumes:
      - ./workspace:/siyuan/workspace
    restart: unless-stopped
    environment:
      # A list of time zone identifiers can be found at https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
      - TZ=${ZEUS_TIMEZONE}
      - PUID=${ZEUS_PUID}  # Customize user ID
      - PGID=${ZEUS_PGID}  # Customize group ID
